
server.port: 8081

spring:
    datasource:
        url: jdbc:postgreesql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
        username: lcsantis
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true

logging:
    level:
        org:
            hibernate:
                type: trace